title = 'mntcloud'
baseURL = 'https://mntcloud.work/'
defaultContentLanguage = 'ru'
summaryLength = 25

[markup]
  [markup.highlight]
    noClasses = false
    lineNos = false


[languages]
[languages.ru]
  contentDir = 'content/ru'
  [languages.ru.menu]
    [[languages.ru.menu.main]]
      name = 'блог'
      url = '/'
      weight = 0
    [[languages.ru.menu.main]]
      name = 'обо мне'
      url = '/about/'
      weight = 0

[languages.en]
  contentDir = 'content/en'
  [languages.en.menu]
    [[languages.en.menu.main]]
      name = 'journal'
      url = '/en/'
      weight = 0
    [[languages.en.menu.main]]
      name = 'about me'
      url = '/en/about/'
      weight = 0